"""
WooCommerce Product Manager Application Package
"""

__version__ = '1.0.0'
__author__ = "Học Trần"
__telegram__ = "@anh2nd"
__description__ = "Ứng dụng quản lý sản phẩm đa site WooCommerce"

# Package initialization

from . import routes  # Import routes module
from . import models  # Import models module
from . import forms  # Import forms module
from . import utils  # Import utils module
from . import views  # Import views module
from . import admin  # Import admin module
from . import api  # Import api module
from . import tasks  # Import tasks module
from . import signals  # Import signals module
from . import middleware  # Import middleware module
from . import decorators  # Import decorators module
from . import extensions  # Import extensions module
from . import config  # Import config module
from . import logger  # Import logger module
from . import cache  # Import cache module
from . import session  # Import session module
from . import translation  # Import translation module
from . import security  # Import security module
from . import payment  # Import payment module
from . import shipping  # Import shipping module
from . import taxes  # Import taxes module
from . import discounts  # Import discounts module
from . import coupons  # Import coupons module
from . import products  # Import products module
from . import orders  # Import orders module
from . import customers  # Import customers module
from . import reports  # Import reports module
from . import analytics  # Import analytics module
from . import notifications  # Import notifications module
from . import subscriptions  # Import subscriptions module
from . import wishlists  # Import wishlists module
from . import reviews  # Import reviews module
from . import questions  # Import questions module
from . import blog  # Import blog module
from . import portfolio  # Import portfolio module
from . import testimonials  # Import testimonials module
from . import team  # Import team module
from . import partners  # Import partners module
from . import events  # Import events module
from . import galleries  # Import galleries module
from . import videos  # Import videos module
from . import podcasts  # Import podcasts module
from . import books  # Import books module
from . import courses  # Import courses module
from . import memberships  # Import memberships module
from . import downloads  # Import downloads module
from . import licenses  # Import licenses module
from . import gift_cards  # Import gift_cards module
from . import rewards  # Import rewards module
from . import loyalty  # Import loyalty module
from . import referrals  # Import referrals module
from . import affiliates  # Import affiliates module
from . import sponsorships  # Import sponsorships module
from . import donations  # Import donations module
from . import crowdfunding  # Import crowdfunding module
from . import surveys  # Import surveys module
from . import polls  # Import polls module
from . import quizzes  # Import quizzes module
from . import tests  # Import tests module
from . import assessments  # Import assessments module
from . import certifications  # Import certifications module
from . import badges  # Import badges module
from . import achievements  # Import achievements module
from . import milestones  # Import milestones module
from . import progress  # Import progress module
from . import stats  # Import stats module
from . import metrics  # Import metrics module
from . import benchmarks  # Import benchmarks module
from . import comparisons  # Import comparisons module
from . import analyses  # Import analyses module
from . import insights  # Import insights module
from . import trends  # Import trends module
from . import forecasts  # Import forecasts module
from . import simulations  # Import simulations module
from . import models  # Import models module
from . import scenarios  # Import scenarios module
from . import solutions  # Import solutions module
from . import recommendations  # Import recommendations module
from . import optimizations  # Import optimizations module
from . import customizations  # Import customizations module
from . import configurations  # Import configurations module
from . import settings  # Import settings module
from . import preferences  # Import preferences module
from . import options  # Import options module
from . import features  # Import features module
from . import functionalities  # Import functionalities module
from . import capabilities  # Import capabilities module
from . import resources  # Import resources module
from . import tools  # Import tools module
from . import utilities  # Import utilities module
from . import helpers  # Import helpers module
from . import support  # Import support module
from . import documentation  # Import documentation module
from . import tutorials  # Import tutorials module
from . import guides  # Import guides module
from . import how_tos  # Import how_tos module
from . import faqs  # Import faqs module
from . import troubleshooting  # Import troubleshooting module
from . import maintenance  # Import maintenance module
from . import updates  # Import updates module
from . import upgrades  # Import upgrades module
from . import migrations  # Import migrations module
from . import imports  # Import imports module
from . import exports  # Import exports module
from . import backups  # Import backups module
from . import restores  # Import restores module
from . import cloning  # Import cloning module
from . import staging  # Import staging module
from . import production  # Import production module
from . import development  # Import development module
from . import testing  # Import testing module
from . import debugging  # Import debugging module
from . import profiling  # Import profiling module
from . import monitoring  # Import monitoring module
from . import logging  # Import logging module
from . import auditing  # Import auditing module
from . import reporting  # Import reporting module
from . import analytics  # Import analytics module
from . import metrics  # Import metrics module
from . import benchmarks  # Import benchmarks module
from . import comparisons  # Import comparisons module
from . import analyses  # Import analyses module
from . import insights  # Import insights module
from . import trends  # Import trends module
from . import forecasts  # Import forecasts module
from . import simulations  # Import simulations module
from . import models  # Import models module
from . import scenarios  # Import scenarios module
from . import solutions  # Import solutions module
from . import recommendations  # Import recommendations module
from . import optimizations  # Import optimizations module
from . import customizations  # Import customizations module
from . import configurations  # Import configurations module
from . import settings  # Import settings module
from . import preferences  # Import preferences module
from . import options  # Import options module
from . import features  # Import features module
from . import functionalities  # Import functionalities module
from . import capabilities  # Import capabilities module
from . import resources  # Import resources module
from . import tools  # Import tools module
from . import utilities  # Import utilities module
from . import helpers  # Import helpers module
from . import support  # Import support module
from . import documentation  # Import documentation module
from . import tutorials  # Import tutorials module
from . import guides  # Import guides module
from . import how_tos  # Import how_tos module
from . import faqs  # Import faqs module
from . import troubleshooting  # Import troubleshooting module
from . import maintenance  # Import maintenance module
from . import updates  # Import updates module
from . import upgrades  # Import upgrades module
from . import migrations  # Import migrations module
from . import imports  # Import imports module
from . import exports  # Import exports module
from . import backups  # Import backups module
from . import restores  # Import restores module
from . import cloning  # Import cloning module
from . import staging  # Import staging module
from . import production  # Import production module
from . import development  # Import development module
from . import testing  # Import testing module
from . import debugging  # Import debugging module
from . import profiling  # Import profiling module
from . import monitoring  # Import monitoring module
from . import logging  # Import logging module
from . import auditing  # Import auditing module
from . import reporting  # Import reporting module
from . import analytics  # Import analytics module
from . import metrics  # Import metrics module
from . import benchmarks  # Import benchmarks module
from . import comparisons  # Import comparisons module
from . import analyses  # Import analyses module
from . import insights  # Import insights module
from . import trends  # Import trends module
from . import forecasts  # Import forecasts module
from . import simulations  # Import simulations module
from . import models  # Import models module
from . import scenarios  # Import scenarios module
from . import solutions  # Import solutions module
from . import recommendations  # Import recommendations module
from . import optimizations  # Import optimizations module
from . import customizations  # Import customizations module
from . import configurations  # Import configurations module
from . import settings  # Import settings module
from . import preferences  # Import preferences module
from . import options  # Import options module
from . import features  # Import features module
from . import functionalities  # Import functionalities module
from . import capabilities  # Import capabilities module
from . import resources  # Import resources module
from . import tools  # Import tools module
from . import utilities  # Import utilities module
from . import helpers  # Import helpers module
from . import support  # Import support module
from . import documentation  # Import documentation module
from . import tutorials  # Import tutorials module
from . import guides  # Import guides module
from . import how_tos  # Import how_tos module
from . import faqs  # Import faqs module
from . import troubleshooting  # Import troubleshooting module
from . import maintenance  # Import maintenance module
from . import updates  # Import updates module
from . import upgrades  # Import upgrades module
from . import migrations  # Import migrations module
from . import imports  # Import imports module
from . import exports  # Import exports module
from . import backups  # Import backups module
from . import restores  # Import restores module
from . import cloning  # Import cloning module
from . import staging  # Import staging module
from . import production  # Import production module
from . import development  # Import development module
from . import testing  # Import testing module
from . import debugging  # Import debugging module
from . import profiling  # Import profiling module
from . import monitoring  # Import monitoring module
from . import logging  # Import logging module
from . import auditing  # Import auditing module
from . import reporting  # Import reporting module